# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.PositiveIntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2)),
            ],
        ),
    ]
