# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistion', '0005_auto_20181102_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
