# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='my_class',
            field=models.ManyToManyField(to='applistions.MyClass'),
        ),
    ]
