# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0004_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('ip', 'port')]),
        ),
    ]
