# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 13:40
from __future__ import unicode_literals

import applistions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0005_auto_20181106_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(null=True, verbose_name='生日')),
                ('gender', models.SmallIntegerField(choices=[(1, '女'), (2, '男'), (3, '保密')], default=1)),
                ('phone_num', applistions.models.MyCharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coding', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applistions.Publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='applistions.Book'),
        ),
    ]
