# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphomework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='companion_age',
            field=models.IntegerField(null=True),
        ),
    ]
