# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(to='applistions.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='c_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applistions.Class'),
        ),
    ]
