# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0002_auto_20181210_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='on_class_time',
            field=models.DateField(null=True),
        ),
    ]
