# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applistions', '0003_student_on_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], null=True),
        ),
    ]
