# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applstion', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('book', models.ManyToManyField(to='applstion.Book')),
            ],
        ),
    ]
